config/routes.rb
Gollazos::Application.routes.draw do

get "home/index"
resources :partidos do
  post 'repartir', on: :collection
  get 'mostrar', on: :collection
  get 'retar', on: :member
  get 'estadio', on: :member
  get 'resultado', on: :member
  resources :bets
end

  get "bet_validation/index"
  get "home/reglamento"
  get "home/contacto"
  get "home/privacidad"

  get "activities/index"
  get "friendship/index"
  get "redireccion/index"
  get "redireccion/new"
  get "metrics/index"
  get "metrics/emails"
  resources :invitations do
    post 'postear', :on => :collection
  end

 resources :users do
    resources :profiles
  end
  resources :redireccion
  resources :friendships
  resources :activities
  
  get "home/index2"

  get "home/invitacion"
  post "home/inivitacion"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match "home/:invitation_token" ,to: "home#referido"
  match "/:invitation_token" ,to: "home#index"

  root :to => 'home#index'
   

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :bets, :dependent => :destroy
	has_many :partidos, :through => :bets, :uniq => true

	has_one :profile

	has_many :friendships
	has_many :friends, :through => :friendships
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key =>"friend_id"
	has_many :inverse_friends, :through => :inverse_friendships, :source => :user


# Include default devise modules. Others available are:
# :token_authenticatable, :confirmable,
# :lockable, :timeoutable and :omniauthable
# Setup accessible (or protected) attributes for your model
#attr_accessible :email, :password, :password_confirmation, :remember_me
#attr_accessible :name, :oauth_expires_at, :oauth_token, :provider, :uid
attr_accessible :name, :oauth_expires_at, :oauth_token, :provider, 
:uid, :pezzos, :administrator, :invitation_token, :visits_number, 
:invitation_number, :invitation_id, :post_on_fb, :bets_number, :age,
:pezzos_que_apuesta, :local_apostado, :visitante_apostado, :referidos,
:pezzos_acumulados, :partidos_ganados, :partidos_perdidos


validates :pezzos, :numericality => {:greater_than_or_equal_to => 0, :message => "no puedes tener menos de 0 pezzos"}
#INVITATION before_create :set_invitation_limit
#----este si se necesita validates_presence_of :invitation_id, :message => 'is required'
#validates_uniqueness_of :invitation_id

has_many :sent_invitations, :class_name => 'Invitation', :foreign_key => 'sender_id'
#belongs_to :invitation


def self.from_omniauth(auth)
	where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
		user.provider = auth.provider
		user.uid = auth.uid
		user.name = auth.info.name
		user.profile = Profile.new
		if auth.info.email == nil

		else
			user.email = auth.info.email
		end

		user.oauth_token = auth.credentials.token
		user.oauth_expires_at = Time.at(auth.credentials.expires_at)
		user.save!    
	end
end


#invitaciones

def facebook
	@facebook ||= Koala::Facebook::API.new(oauth_token)
end

def friends_count
	facebook.get_connection("me","friends").size
end

def descontar_pezzos(monto)
	pezzos_total = self.pezzos - monto
	self.update_attributes(pezzos: pezzos_total)
end
def consignar_pezzos(monto)
	pezzos_total = self.pezzos + monto
	self.update_attributes(pezzos: pezzos_total)
end
def aumentar_visitas
	visitas_total = self.visits_number + 1
	self.update_attributes(visits_number: visitas_total)
end
def aumentar_invitaciones
	invitaciones_total = self.invitation_number + 1
	self.update_attributes(invitation_number: invitaciones_total)
end
def aumentar_referidos
	referidos_total = self.referidos + 1
	self.update_attributes(referidos: referidos_total)
end
def aumentar_apuestas
	apuestas_total = self.bets_number + 1
	self.update_attributes(bets_number: apuestas_total)
end
def aumentar_posts
	posts_total = self.post_on_fb + 1
	self.update_attributes(post_on_fb: posts_total)
end

def position(column = 'pezzos', order = 'DESC')
	order_by = "#{column} #{order}"
	arrow = order.capitalize == "ASC" ? "<=" : ">="
	User.where("#{column} #{arrow} ?", self.send(column)).order(order_by).count
end  
def followers
	followers = []
	self.inverse_friends.each do |follower|
		followers.push(follower)
	end
	return followers
#return self.inverse_friendships
end

def followers_ids
	followers = []
	self.followers.each do |follower|
		followers.push(follower.id)
	end
	return followers
end


def following
	following = []
	self.friendships.each do |follower|
		following.push(follower.friend)
	end
	return following
end

def following_ids
	following = []
	self.following.each do |follower|
		following.push(follower.id)
	end
	return following
end

def self.correos_usuarios
	usuarios = User.where("email is NOT NULL", nil)
	return usuarios
end

def montos_que_puede_apostar
	maxApostable = 100000
	maxApuestaPersonal = maxApostable > self.pezzos ? self.pezzos : maxApostable 
	monto= 10000
	montos =[]
	while monto <= maxApuestaPersonal #self.pezzos
		montos.push(monto)
		monto+=10000
	end
	return montos
end

def frase_de_ganador
	frases=["La sacaste del estadio.",
		"Anotate un 10.",	
		"Muy bien, campeon.",
		"Ya en el barrio te dicen Messi.",
		"Excelente, aplausos.",
		"Un 'diez' aclamado.",
		"La perfeccion tiene tu nombre.",
		"Palmas y ovaciones."]
	return frases.sample
end
def frase_de_perdedor
	frases=["Sigue participando.", 
		"Un mal dia lo tiene cualquiera, No pierdas la fe.",
		"Si Messi bota golazzos, tu tambien tienes derecho a fallar.",
		"Animo, Sigue adelante.",
		"No hay problema, En la vida siempre hay revancha.", 
		"La practica hace al maestro, Intenta otra vez.",
		"A los mejores tambien les pasa, Hay tiempo para mejorar.",
		"el que persevera, alcanza",
		"Paciencia, la practica hace al maestro."]
	return frases.sample
end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ActionController::Base
  protect_from_forgery
  def facebook

     # with this code you can see the data sent by facebook
     omniauth = request.env["omniauth.auth"] 

    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      #@user.consignar_pezzos(50000)
      session[:user_id]= @user.id
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login

  def index
    @users= User.paginate(page: params[:page], per_page: 15).order("pezzos DESC")
    if params[:page]==nil
      @page = 1
    else
      @page = ((params[:page].to_i - 1) * 15) + 1  
    end

  end

  def show
    #Golazzos 1
    @user= User.find(params[:id])
    #if @user.profile ==nil
    #  @user.profile =Profile.new
    #end

    #if @user.partidos.any?
      #if params[:partidoId]
       # @partido= Partido.find(params[:partidoId])
      #else
       # @partido = @user.partidos.first
      #end

      #@bets= @partido.bets.where("user_id = ?", @user.id) 
    #end   
    #@pezzos_por_amigos= User.where('invitation_id = ?', @user.id).count * 50000
    #@pezzos_por_amigos= @user.referidos * 5000
    #@pezzos_por_actividad= @user.bets.count * 5000


    #golazzos2.0
    #@friends= @user.following


    @partidos = @user.partidos.includes(:bets).order("diapartido DESC")

    @followings = [@user.id]
    if @user !=current_user
      @followings = @followings + current_user.following_ids
      @followings = @followings.uniq
    end

    #@bets = Bet.limit(10).find(:all, conditions: { user_id: @followings}, order: "created_at DESC")
    @bets = Bet.includes(:user).limit(10).where(user_id:@followings).order("created_at DESC")
    @ranking =@user.following
    @ranking.push(@user)
    #@friends = @ranking.sort_by! {|u| u.pezzos_acumulados}
    @friends = @ranking.sort { |x,y| y.pezzos_acumulados <=> x.pezzos_acumulados }
  end

  def update
  	current_user.update_attributes(params[:user])
    @partido = Partido.find(params[:partido_actual_id])
    respond_to do |format|
      format.html { redirect_to :back}
      format.js
    end
  end

end

app/views/users/_apuestas_partidos.html.haml
-@partidos.each do |partido|
	%section 
		.MiApuesta
			%article.cajamarcadorDos 
				.marcadorCentrado
					.escudoequipo
						=image_tag partido.logolocal
						%h3=partido.local
					.datospartido
						.liga
							=partido.nombre_torneo
						.vs
							="#{partido.resultadoLocal} - #{partido.resultadoVisitante}"
						.hora
							=partido.hora_partido
						.pjugando
							=pluralize(partido.users.uniq.count, "persona")
							jugando
						%div
							-if partido.terminado
								=link_to "Ir al Resultado", resultado_partido_path(partido)
							-else
								=link_to "Ir al Estadio", estadio_partido_path(partido)
					.escudoequipo
						=image_tag partido.logovisitante
						%h3=partido.visitante
		%table.table.tablapartidos
			%thead 
				%tr 
					%th
						%small Marcador
					%th 
						%small Apuesta
					%th
						%small 
							-if partido.cerrado
								.MiApuestaRetornoFinal
									Retorno garantizado
							-else
								.MiApuestaRetornoEstimado
									Retorno estimado
					%th
						%small Ganancia
					%th
			%tbody
				-@user.bets.where("partido_id = ?",partido.id).each do |bet|
					%tr
						%td= "#{bet.golesLocal} - #{bet.golesVisitante}"
						%td= number_to_currency bet.monto, precision: 0

						-if bet.partido.repartido
							%td 
								.MiApuestaRetornoFinal
									=number_to_currency bet.partido.xveces_el_resultado(bet.golesLocal, bet.golesVisitante)* bet.monto, precision:0
							-if bet.pezzos_ganados==nil
								%td 
									.MiApuestaPerdi
										=number_to_currency bet.monto * -1, precision: 0
								%td
									=image_tag "golazzos2/triste.png", alt:"triste"  
							-else
								%td 
									.MiApuestaGane
										=number_to_currency bet.pezzos_ganados, precision: 0
								%td
									=image_tag "golazzos2/feliz.png", alt:"feliz" 

						-elsif bet.partido.cerrado
							%td
								.MiApuestaRetornoFinal
									= number_to_currency bet.partido.xveces_el_resultado(bet.golesLocal, bet.golesVisitante)* bet.monto, precision: 0
							%td ¡Jugandose!
							%td

						-elsif bet.partido.cerrado==false
							%td 
								.MiApuestaRetornoEstimado
									= number_to_currency bet.partido.xveces_el_resultado(bet.golesLocal, bet.golesVisitante)* bet.monto, precision: 0
							%td ¡Por jugar!
							%td

app/views/users/_user_apostaria.html.erb
<div class="alert alert">
    <strong>Te gustaría poder apostar dinero real por tus equipos favoritos?</strong> <br/> 
    <div class="formulario-sameline">
      <%= form_for [current_user, current_user.profile], :html => { :class => 'form-horizontal' } do |f| %>
        <%= f.hidden_field :apostaria, value: true %>
        <button   class="btn btn-primary" data-dismiss="ale2rt">
        Si, deseo apostar dinero real!
        <% f.submit ""%> 
        </button> 
      <%end%>
    </div>

    <div class="formulario-sameline">
      <%= form_for [current_user, current_user.profile], :html => { :class => 'form-horizontal' } do |f| %>
        <%= f.hidden_field :apostaria, value: false %>
        <button   class="btn" data-dismiss="ale2rt">
        No
        <% f.submit ""%> 
        </button> 
      <%end%>
    </div>
</div>
 

app/views/users/_user_mi_perfil.html.erb
<div class="span9 BTSinEspacio">
<p class= "lead">¡Hola <font face="FUTURAB" color="#005798"><%=@user.name%></font>! </p>
<p><font face="FUTURAB" color="#005798">TIENES</font><font size="18" face="digital7" color="orange"><%=number_to_currency(current_user.pezzos,:precision => 0)%></font> <font face="FUTURAB" color="#005798">PEZZOS</font>     / ACTUALMENTE ESTAS EN LA POSICIÓN <strong><font size="18" color="#005798"><%=@user.position%></font></strong> DEL RANKING</p>
<%= link_to  new_invitation_path do%>
	<%= image_tag "user/btnGanarPezzos_menu.png"%>
<%end%>
<%= render "user_profile"%>
</div>
<font face="Futura Book BT">

app/views/users/_user_profile.html.erb
<a href="" data-toggle="modal" data-target="#myProfile">
  Actualizar mi Perfil
</a>
<div id="myProfile" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<%= form_for [@user, @user.profile], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">¡Actualizar Mi Perfil!</h3>
  </div>

  <div class="modal-body">

  <div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Obtén $50,000 pezzos llenando tu perfil!</strong> <br/> Actualiza la información de tu perfil para ganar mas pezzos.
  </div>
  <div class="control-group">
    <%= f.label :pais, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :pais, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :ciudad, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ciudad, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :direccion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :direccion, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :celular, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :celular, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :twitter, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :twitter, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :equipos_favoritos, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :equipos_favoritos, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :camiseta_de, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :camiseta_de, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :talla, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :talla, :class => 'text_field' %>
    </div>
  </div>
  </div>
  <div class="modal-footer">
  
	<%= f.hidden_field :nombre, value: @user.name%>
    <button class="btn">
    	Actualizar Perfil
		<% f.submit ""%> 
    </button>	
       
  </div>
  <%end%>
</div>

app/views/users/_user_profile_boton.html.erb
<button href="" data-toggle="modal" data-target="#myProfile" class="btn btn-primary">
  Actualizar mi Perfil
</button>
<div id="myProfile" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<%= form_for [@user, @user.profile], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">¡Actualizar Mi Perfil!</h3>
  </div>

  <div class="modal-body">

  <div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Obtén $50,000 pezzos llenando tu perfil!</strong> <br/> Actualiza la información de tu perfil para ganar mas pezzos.
  </div>
  <div class="control-group">
    <%= f.label :pais, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :pais, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :ciudad, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ciudad, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :direccion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :direccion, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :celular, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :celular, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :twitter, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :twitter, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :equipos_favoritos, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :equipos_favoritos, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :camiseta_de, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :camiseta_de, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :talla, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :talla, :class => 'text_field' %>
    </div>
  </div>
  </div>
  <div class="modal-footer">
  
	<%= f.hidden_field :nombre, value: @user.name%>
    <button class="btn">
    	Actualizar Perfil
		<% f.submit ""%> 
    </button>	
       
  </div>
  <%end%>
</div>

app/views/users/_user_tu_perfil.html.erb
<div class="span9 BTSinEspacio">
<p class= "lead"><font face="FUTURAB" color="#005798"><%=@user.name%></font>!</p>
<p><font face="FUTURAB" color="#005798">TIENE </font><font size="18" face="digital7" color="ffd200"><%=@user.pezzos%></font> <font face="FUTURAB" color="#005798">PEZZOS</font>     / ACTUALMENTE ESTÁ EN LA POSICIÓN <strong><font size="18" color="#005798"><%=@user.position%></font></strong> DEL RANKING</p>
<%= link_to  new_invitation_path do%>
	<%= image_tag "user/btnGanarPezzos_menu.png"%>
<%end%>
</div>
<font face="Futura Book BT">

app/views/users/index.html.erb
<!-->
  <div class= "header-title">
  <div class="container">
    <div class="row">
      <div class="span6 fuenteFuturaB titulo-blanco">
        <p> <p>
        <h3><%=image_tag "ranking/btn_rankingTitulos.png"%>JUGADORES</h3>
      </div>
    </div>
  </div>
</div>

      
  <table class="table">
    <thead>
      <tr>
        <th>Posición</th><th>Nombre</th><th>Pezzos</th><th># Apuestas</th>
      </tr>
    </thead>
    <tbody>
      <%count = @page %>
      <%@users.each do |user|%>
        <tr>
          <td>
            <%=count%>
          </td>
          <td>
            <div class="jugador">
              <%=image_tag current_user.facebook.get_picture(user.uid, {type: "square"}), {:class=> "", :width=>"30"}%>  <%=link_to user.name, user%></span></td><td><%= number_to_currency(user.pezzos,:precision => 0)%></td><td><%= user.bets.count%></td>
            </div>
        </tr>
        <%count +=1%>
      <%end%>
    </tbody>
  </table>
  
</div>
<%= will_paginate %>
  </div>
</div></!-->

app/views/users/show.html.erb
<section class="cperfil">
    <div class="modulo1">
        <div class="fotoperfil">
            <%=image_tag current_user.facebook.get_picture(@user.uid, {type: "large"}), :class=>"img-rounded"%>
        </div>
        <div>
            <%= link_to "Partidos", partidos_path, {:class => "botonGolazzos"} %>
        </div>
    </div>
    <div class="modulo2">
        <div class="nombreperfil"><%= @user.name %> </div>
        <div class="boxpezzos">
            <div class="topicpezzos">Pezzo$</div>
            <div class="cantidadpezzos"><%= number_to_currency @user.pezzos,  precision:0%></div>
        </div>
        <div class="boxdinero">
            <div class="topicdinero">Dinero</div>
            <div class="cantidaddinero">0</div>
        </div>
        <div class="modulo3">

            <div class="logrosuser">
                <div class="nombrelogro" id="puntos">$ Ganados</div>
                <div class="numerologro"><%=number_to_currency @user.pezzos_acumulados,  precision:0%></div>
            </div>
            <div class="logrosuser">
                <div class="nombrelogro" id="ganados">Ganados</div>
                <div class="numerologro"><%= @user.partidos_ganados %></div>
            </div>
            <div class="logrosuser">
                <div class="nombrelogro" id="perdidos">Perdidos</div>
                <div class="numerologro"><%= @user.partidos_perdidos %></div>
            </div>
        </div>
    </div>
</section>
<ul class="nav nav-tabs">
  <li class ="active"><a href="#actividades" data-toggle="tab" >Actividad</a></li>
  <li><a href="#ultimas_apuestas" data-toggle="tab">Apuestas</a></li>
  <li><a href="#amigos" data-toggle="tab">Competencia</a></li>
</ul>

<div class="tab-content">
    <div id="actividades" class="tab-pane active">
        <section>
            <% @bets.each  do |bet| %>
            <div class="boxuser bloque">
                <div class="boxuserpadding">
                    <div class="fotoestado">
                        <div class="apuestacolor"></div>
                        <div class="fotperfil">
                            <%=image_tag current_user.facebook.get_picture(bet.user.uid)%>
                        </div>
                        <div class="estado">
                            <% if !bet.partido.terminado%>
                            <!-- No se agrega ninguna carita. -->
                            <%elsif bet.pezzos_ganados.to_i > 0 %>
                            <%= image_tag "golazzos2/feliz.png", alt:"ok" %>
                            <%else %>
                            <%= image_tag "golazzos2/triste.png", alt:"ok" %>
                            <% end %>

                        </div>
                    </div>
                    <div class="textosperfil">
                        <div class="names">
                            <%=link_to bet.user.name, user_path(bet.user) %>
                            <small class="timeago"><%=distance_of_time_in_words( bet.created_at, Time.now) %> ago</small>
                        </div>
                        <div class="textopublicacion" >
                            Jugó
                            <strong class="pezzares">
                            <%=number_to_currency bet.monto, precision:0%>   
                            </strong>
                            pezzos a
                            <strong class="pezzares">
                            <%= link_to "#{bet.partido.local} #{bet.golesLocal} - #{bet.golesVisitante} #{bet.partido.visitante}", bet.partido %>
                            .
                            </strong>

                            <!-- EL PARTIDO NO A EMPEZADO -->
                            <%if !bet.partido.cerrado %>
                            ¡Apuesta y reta a tus amigos!
                            <%= link_to "ir al partido.", bet.partido %>

                            <!-- EL PARTIDO YA EMPEZO Y NO A TERMINADO -->
                            <%elsif !bet.partido.terminado %>
                            ¡El partido ya empezo, no se aceptan mas apuestas!

                            <!-- GANO LA APUESTA -->
                            <%elsif bet.pezzos_ganados.to_i >0  %>
                                    Gano
                                    <strong class="pezzares">
                                    <%= number_to_currency bet.pezzos_ganados, precision:0 %>
                                    </strong>
                                    . <%= current_user.frase_de_ganador %>
                                    
                            <!-- PERDIO LA APUESTA -->
                            <%else %>
                                    Perdio
                                    <strong class="pezzares">
                                    <%= number_to_currency bet.pezzos_ganados, precision:0 %>
                                    </strong>
                                    . <%= current_user.frase_de_perdedor %>
                            <%end %>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>
        </section> 
    </div>
    <div id="ultimas_apuestas" class="tab-pane">
        <%= render "apuestas_partidos"%>
    </div>
<div id="amigos" class="tab-pane">
    <section id="resultadoDeAmigos">

        <table class="table tablapartidos">
            <thead>
                <tr>
                    <th></th>
                    <th><small>Amigo</small></th>
                    <th><small>$ ganados</small></th>
                    <th><small> Ganados</small></th>
                    <th><small> Perdidos</small></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

             <% @friends.each_with_index  do |friend, i| %>
             <tr class=<%= "grismio" if friend.id == @user.id %>>

                <td>
                    <%= i +1 %>
                    <%case i %>
                    <% when 0 %>
                    <div class="oro"></div>
                    <% when 1%>
                    <div class="plata"></div>
                    <% when 2 %>
                    <div class="bronce"></div>
                    <%end  %>
                    
                </td>
                <td>
                    <%=link_to friend.name, user_path(friend) %>
                </td>
                <td>
                    <%= friend.pezzos_acumulados %>
                </td>
                <td><%= friend.partidos_ganados %></td>
                <td><%= friend.partidos_perdidos %></td>
                <td></td>
            </tr>
            <%end%>
            
        </tbody>
    </table>
    <br>

    <div class="MiApuesta" style="height:40px !important;">
        <h3>
            Comenta la Competencia con tus Amigos
        </h3>
    </div>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

    <div class="fb-comments" data-href="http://goldos.herokuapp.com/partidos" data-colorscheme="light" data-numposts="10"></div>


    <style type="text/css">
    .fb-comments, .fb-comments span, .fb-comments.fb_iframe_widget span iframe {
        width: 100% !important;
    }
    </style>


    <script type="text/javascript">
    $('.fb-comments').attr('data-href',window.location.href);
    </script>

    <div id="fb-root"></div>
</section>
</div>
</div>

app/views/users/update.js.erb
$("#botonesmontos").html("<%= escape_javascript(render('partidos/apuesta_diez')) %>");
$("#matriz").html("<%= escape_javascript(render('partidos/botones_apuestas')) %>");
$("#formulario").html("<%= escape_javascript(render('partidos/formulario_apuesta')) %>");