config/routes.rb
Gollazos::Application.routes.draw do

get "home/index"
resources :partidos do
  post 'repartir', on: :collection
  get 'mostrar', on: :collection
  get 'retar', on: :member
  get 'estadio', on: :member
  get 'resultado', on: :member
  resources :bets
end

  get "bet_validation/index"
  get "home/reglamento"
  get "home/contacto"
  get "home/privacidad"

  get "activities/index"
  get "friendship/index"
  get "redireccion/index"
  get "redireccion/new"
  get "metrics/index"
  get "metrics/emails"
  resources :invitations do
    post 'postear', :on => :collection
  end

 resources :users do
    resources :profiles
  end
  resources :redireccion
  resources :friendships
  resources :activities
  
  get "home/index2"

  get "home/invitacion"
  post "home/inivitacion"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match "home/:invitation_token" ,to: "home#referido"
  match "/:invitation_token" ,to: "home#index"

  root :to => 'home#index'
   

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index


    redirect_to user_path(current_user) if current_user #redireccionar al usuario si esta logeado

    @partidos = Partido.where("diapartido > ?", Time.now).order("diapartido ASC").limit(3)
    #track_ga_event("Users", "Login", "Standard")
    #@partido = Partido.find(64)
  end
  def index2
  end
  def reglamento
    
  end
  def contacto
    
  end

  def invitacion
    @mensaje = params[:mensaje]
    @fbUser = params[:fbUser]
    current_user.facebook.put_wall_post("prueba prueba golazzos @antonio.faillace.96", {:name => "i love loving you", :link => "http://www.explodingdog.com/title/ilovelovingyou.html"}, "antonio.faillace.96" )
  end

  def referido
  		
    #Revisa si esta invitado o no esta invitado para mostrar un mensaje.  
  	
    @invitacion= User.find_by_uid(params[:invitation_token])
    session[:guacamaya]=params[:invitation_token]

    if @invitacion==nil
      #flash[:notice] = "Invitación no válida"  
    else
      flash[:notice] = "Has sido invitado a Golazzos, registrate y redime 50.000 Pezzos gratis!"  
    end

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-interval="3000">

  <!-- Carousel items -->
  <div class="carousel-inner centro">
    <div class="active item">
<%=image_tag "landing/banner/bannerImagen_1_new.jpg", {:class => "", :width=>""}%> 
    </div>
    <div class="item">
<%=image_tag "landing/banner/bannerImagen_2.jpg", {:class => "", :width=>""}%> 
    </div>
    <div class="item">
<%=image_tag "landing/banner/bannerImagen_4.jpg", {:class => "", :width=>""}%> 
    </div>
        <div class="item">
<%=image_tag "landing/banner/bannerImagen_5.jpg", {:class => "", :width=>""}%> 
    </div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

app/views/home/contacto.html.erb
 <h2 class="titulosseccion">CONTACTANOS</h2>
 
     <div class="wrapper ">
      <p class="emailcontacto">
        Para contactarte con nosotros , envianos un email a:
      </p>
          <%= link_to "infogolazzos@gmail.com", "#", {:class => "botpezzos"} %> 
     </div>

<div class="emailcontacto">
  <%= image_tag "partido/partido_fondoPersonaje.png"%>
</div>

app/views/home/index.html.erb
  <% if flash[:notice]%>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
  <% end %>

  <section id="bienvenida">
    <div id="myCarousel" class="carousel slide">
      <!-- Carousel items -->
      <div class="carousel-inner">
        <div class="active item">
          <%= image_tag "golazzos2/banner1.png" %>
        </div>
        <div class="item">
          <%= image_tag "golazzos2/banner2.png" %>
        </div>
        <div class="item">
          <%= image_tag "golazzos2/banner3.png" %>
        </div>
      </div>
      <!-- Carousel nav -->
      <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
      <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
    <h1 class="frasehome"> APUESTAS EN FÚTBOL RETANDO A TUS AMIGOS</h1>
    <%= render "partidos/redes_sociales" %>
  </section>      

  <section id="partidosSabrozzos" class="clear">
    <header >
      <h2 class="titulosseccion clear">PARTIDOS SABROZZOS</h2>
    </header>  
    <%@partidos.each do |partido| %>
    <a href=<%= partido_path(partido)%>> 
      <article class="cajamarcador">
        <div class="marcadorCentrado">
          <div class="escudoequipo">
           <%= image_tag partido.logolocal %>
           <h3> <%= partido.local %></h3>
         </div>
         <div class="datospartido">
          <div class="Liga"><%= partido.nombre_torneo %></div>
          <div class="vs">VS</div>
          <div class="hora"><%= partido.hora_partido %></div>
          <%if partido.users.uniq.count >=10%>
            <div class="pjugando2"><%= pluralize(partido.users.uniq.count, "persona") %> jugando</div>
          <%end%>
        </div>
        <div class="escudoequipo">
          <%= image_tag partido.logovisitante %>
          <h3> <%= partido.visitante %></h3>
        </div>
      </div>
      <div class="botcontinuar"></div>
    </article>
  </a>
  <%end %>
  <div class="masPartidos"><%= link_to "ver mas partidos", partidos_path %></div> 
</section>

<section id="sobreGolazzos" class="">
  <header>
    <h2 class="titulosseccion">SOBRE GOLAZZO$</h2>
  </header>
  <p class="wrapper" id="frase1">Golazzo$ es un juego divertido donde puedes ganar dinero retando a tus amigos a los marcadores finales de tus equipos favoritos. Funciona en (3) simples pazzos.</p>

  <div class="pasos">
    <%= image_tag "golazzos2/paso1.png", :class=> " pull-left", :width=> "80px" %>
    <h3 class="wrapper" id="frase1">
      Pazzo 1
    </h3>
    <p class="wrapper">
      <strong class="bold">
        SELECCIONA 
      </strong> 
      Tu partido y tu marcador esperado que te dará una ganancia si aciertas
    </p>
  </div>
  <div class="pasos">
    <%= image_tag "golazzos2/paso2.png", :class=> " pull-left", :width=> "80px" %>
    <h3 class="wrapper" id="frase1"> 
      Pazzo 2
    </h3>
    <p class="wrapper">
      <strong class="bold">
        RETA
      </strong> 
      A tus amigos y apuestas con dinero real o ficticio que llamamos "pezzo$"
    </p>
  </div>
  <div class="pasos">
    <%= image_tag "golazzos2/paso3.png", :class=> " pull-left", :width=> "80px" %>
    <h3 class="wrapper" id="frase1">
      Pazzo 3
    </h3>
    <p class="wrapper">
      <strong class="bold">
        COMPARTE
      </strong>
      tu pasión en nuestro "Estadio" donde comentas el partido. Ganas si aciertas el marcador.
    </p>
  </div>

  <div class="masPartidos"></div>
</section>
<section class="titulosseccion ">
  <h2 class="reglamentoGolazzos">
    <%= link_to "REGLAMENTO", home_reglamento_path %>
  </h2>
</section>

app/views/home/index2.html.erb
Home#Index2.html

<!--><center>
  <div class="fondo-redireccion">
    <%=image_tag "landing/fondo.png", {:class => "", :width=>""}%> 
  </div>
<div class="redireccion">
<img src="http://farm9.staticflickr.com/8250/8569530893_68e5c4ddce_b.jpg" width="520" height="1174" border="0" usemap="#Map" />
<map name="Map" id="Map">
  
  <area shape="rect" coords="90,185,430,237" href="http://www.golazzos.com/" target="_blank" />
  <area shape="rect" coords="72,953,452,1011" href="http://www.golazzos.com/" target="_blank" />
</map>
</div>
</center>
</!-->

app/views/home/invitacion.html.erb
invitacion.html.erb

<h1>Mensaje al muro</h1>
<%= form_tag do %>
	<%= label_tag :fbUser %>
	<%= text_field_tag :fbUser %>
	<%= label_tag :mensaje %>
	<%= text_field_tag :mensaje %>
	<%= submit_tag "mandar mensaje" , {:class => "btn"} %>
<% end %>

app/views/home/privacidad.html.erb
<h2 class="titulosseccion">POLITICAS DE PRIVACIDAD</h2>
<div class="wrapper">
		Estamos creando la comunidad futbol online mas respetuosa... 
		"No te dejes sacar tarjeta roja". Sigue estas simples reglas..
		<ol>
			<li>Solo reta amigos que conoces. A ese que conociste en una fiesta hace 3 anos y no lo volviste a ver es mejor que no lo retes.</li>
			<li>Solo reta amigos que les guste el fútbol. No pierdas el tiempo retando a tu abuelita que nunca a cantado un golazzo! </li>
			<li>Aprovechas y Incluye en el espacio un "saludito" a tus amigos. </li>
		</ol>
		Si piensas que tu privacidad esta comprometida escribenos ya a <strong>infogolazzos@gmail.com</strong> y tomaremos medidas al
		respecto. Sacaremos tarjetas amarillas y rojas si es necesario.
</div>

app/views/home/referido.html.erb
Home#referido.html
<!-->
<div class="contenedor">

  <div id="apDiv2"><%= image_tag "secciones/premios3.png"%>
   <div class="botonFacebook">

<%= link_to "/auth/facebook" do%>
 <%= image_tag ('Call/btnCall.png')  %>
 <% end -%>
  </div>
  </div>
</div>

<div class="container">

<pre>Has sido referido con el token:

<%= session['guacamaya'] %>

</pre>
</div>
</!-->

app/views/home/reglamento.html.erb
<h2 class="titulosseccion">REGLAMENTO</h2>
<div class="wrapper">



	<h2>1. ¿QUÉ ES GOLAZZO$?</h2>

	Golazzo$ es una plataforma online donde juegas y apuestas al fútbol retando a tus amigos.La idea es divertirse compartiendo tu pasión por el fútbol acertando marcadores de tus equipos favoritos.

	<h2>2. ¿CÓMO FUNCIONA GOLAZZO$?</h2>
	Golazzo$ funciona en 3 simples paZZos.
	<ol>
		<li><strong>SELECCIONA</strong> tu partido y tu marcador esperado que te dará una ganancia si aciertas.</li>
		<li><strong>RETA</strong> a tus amigos y apuestas con dinero real o ficticio que llamamos "pezzo$".</li>
		<li><strong>COMPARTE</strong> tu pasión en nuestro "Estadio" donde comentas el partido. y Ganas si aciertas el marcador.</li>
	</ol>
	<h2>3. ¿QUÉ SON PEZZO$?</h2>
	En Golazzo$ te ofrecemos la opción de jugar dinero ficticio o dinero real (¡pronto!). El dinero ficticio lo llamamos pezzo$.
	<h2>4. ¿CÓMO OBTENDRÁS PEZZO$?</h2>
	Existen 4 formas de obtener dinero ficticio
	<ol>
		<li><strong>POR REGISTRARTE:</strong> Cuando te registras en Golazzo$ te damos 100,000 pezzo$</li>
		<li><strong>POR JUGAR:</strong> Cuando juegas por marcadores te damos 10,000 pezzo$ por tu actividad</li>
		<li><strong>POR RETAR:</strong> Cuando retas a tus amigos por cada amigo que acepte tu reto por primera vez les damos 50,000 pezzo$ a los dos. Por otros retos enviados y aceptados les damos 25,000 pezzo$ a los dos.</li>
		<li><strong>POR GANAR:</strong> Cuando juegas por un marcador en un partido y aciertas el marcador final obtendrás un retorno al dinero ficticio que jugaste. Por ejemplo si juegas 10,000 pezzo$ al marcador 1-1 podrías por ejemplo recibir 40,000 pezzo$ si aciertas.</li>
	</ol>
	<h2>5. ¿PUEDO JUGAR DINERO REAL EN GOLAZZO$?</h2>
	Por ahora sólo puedes jugar dinero ficticio.

	<h2>6. ¿QUÉ TIPO DE RETORNOS HAY EN GOLAZZO$?</h2>
	Golazzo$ tiene un modelo de retornos dinámicos. Esto significa que el retorno final se garantiza una vez comience el partido y se cierran las apuestas. Hay 4 tipos de retornos en Golazzo$:
	<ol>
		<li><strong>RETORNO ESTIMADO:</strong> Cuando seleccionas un marcador y un monto de dinero real o ficticio a jugar se te muestra un retorno estimado. Este el retorno es basado en la bolsa de dinero en ese momento en el partido y puede cambiar de acuerdo a la oferta y la demanda por marcadores hasta que comience el partido. Entre más amigos retes a ese partido más podría aumentar tu retorno.</li>
		<li><strong>RETORNO MÍNIMO GARANTIZADO: </strong>Indepedientemente de la oferta y la demanda por marcadores nosotros te ofrecemos un retorno mínimo garantizado si aciertas ese marcador. </li>
		<li><strong>RETORNO FINAL GARANTIZADO:</strong> Apenas comience el partido y se cierren las apuestas se confirma el retorno final que te garantiza en ese marcador en el caso que aciertes.</li>
		<li><strong>RETORNO FINAL: </strong>Cuando termine el partido y se sepa el marcador te mostraremos tu ganancia si acertaste o tu perdida si no.</li>
	</ol>

	<h2>7. ¿CÓMO PUEDO AUMENTAR MI RETORNO CUANDO JUEGO A UN MARCADOR?</h2>
	Entre más amigos retes en Golazzo$ más puede aumentar tu retorno.

	<h2>8. ¿CUÁNDO SE CIERRAN LOS PARTIDOS?</h2>
	Los partidos se cierran aproximadamente 15 minutos antes de su comienzo.

	<h2>9. ¿CUÁNDO SE REPARTE EL DINERO DE LOS MARCADORES QUE ACERTARON?</h2>
	Se reparte dentro las 24 horas siguientes a la finalización del partido

	<h2>10. ¿CÓMO RETO A MIS AMIGOS EN GOLAZZO$?</h2>
	En la sección de "El RETO" primero aceptas los "términos y condiciones" de Privacidad y después utilizas el Facebook "send button" para enviarle el Reto con un mensaje personalizado a los amigos que quieres retar.

	<h2>11. ¿CUÁLES SON NUESTRAS POLÍTICAS DE PRIVACIDAD?</h2>
	Estamos creando la comunidad de fanáticos más respetuosa. Encuentra <%= link_to "AQUÍ", home_privacidad_path %> nuestras políticas de privacidad. En general, no promovemos ni incentivamos el SPAM. Por eso solo RETA amigos que conoces y que les gusta el fútbol y los cuales crees apreciarían tu invitación. Escríbeles en el "SEND BOX" un saludo personalizado.

	<h2>12. ¿CUÁNTO Y CUÁNTAS VECES PUEDO APOSTAR POR PARTIDO?</h2>
	 Ofrecemos que los jugadores puedan jugar entre $10,000 y $100,000 pezzo$ por marcador Puedes además el número de marcadores que desees. No hay límite.

	<h2>13. ¿POR QUÉ NO PUEDO JUGAR POR ALGUNOS MARCADORES?</h2>
	Excepcionalmente algunos marcadores se bloquean por un tiempo para asegurar que hay suficiente dinero para pagar el RETORNO MÍNIMO GARANTIZADO en ese marcador. En el momento que podamos asegurar que se puede pagar el marcador se vuelve a habilitar.

	<h2>14. ¿CÓMO NOS PONEMOS EN CONTACTO CON USTEDES?</h2>
	Nos gustan los comentarios sean buenos o malos. Los tomamos muy en serio. Puedes escríbirnos por el boton de feedback o escríbirnos a infoGolazzo$@gmail.com. También nos puedes escribir a tráves de tu cuenta en twitter a @Golazzos.
</div>